# Generated by Django 6.0.2 on 2026-05-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interpret',
            fields=[
                ('interpret_id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Interpret',
                'verbose_name_plural': 'Interpreti',
                'db_table': 'Interpreti',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('datum_zalozeni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labely',
                'db_table': 'Labely',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_turne', models.CharField(max_length=255)),
                ('prvni_koncert', models.CharField(max_length=255)),
                ('kapacita', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Turné',
                'verbose_name_plural': 'Turné',
                'db_table': 'Tour',
            },
        ),
        migrations.CreateModel(
            name='Diskografie',
            fields=[
                ('diskografie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=255)),
                ('datum_vydani', models.IntegerField()),
                ('poslechy', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('Album', 'Album'), ('Single', 'Single'), ('Duet', 'Duet')], max_length=20)),
                ('interpret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diskografie', to='Interpreti.interpret')),
            ],
            options={
                'verbose_name': 'Diskografie',
                'verbose_name_plural': 'Diskografie',
                'db_table': 'Diskografie',
            },
        ),
        migrations.AddField(
            model_name='interpret',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interpreti', to='Interpreti.label'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Hlavní interpret', 'Hlavní interpret'), ('Předkapela', 'Předkapela')], max_length=50)),
                ('interpret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vystoupeni', to='Interpreti.interpret')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='Interpreti.tour')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Program',
                'db_table': 'Program',
            },
        ),
    ]
