# Generated by Django 6.0.2 on 2026-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interpreti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpret',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='interpreti/'),
        ),
    ]
