# Generated by Django 6.0.2 on 2026-06-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interpreti', '0002_interpret_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskografie',
            name='datum_vydani',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
